theme: jekyll-theme-minimal
title: Collins Mutugi Riungu
description: Experienced Full Stack Developer adept in bringing forth expertise in design, installation, testing and maintenance of software systems
